---
title: "Random forest - Multiclass"
author: "Rohan Chopra"
date: "August 21, 2017"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

```{r}
setwd("~/coding/Envible-VITVellore-AMAX-Analyze-This-2017")
```

```{r}
data <- read.csv('Dataset/Training_Dataset.csv')
```

```{r}
str(data)
```
```{r}
str(as.factor(data$mvar45))
```

```{r}
summary(data)
```


Dropping mvar1 and cm_key

```{r}
data <- data[, ! names(data) %in% c("mvar1"), drop = FALSE]
data <- data[, ! names(data) %in% c("cm_key"), drop = FALSE]
```

```{r}
head(data)
```

```{r}
data$target <- rep("None",nrow(data))
data$target[data$mvar49==1] <- "Supp"
data$target[data$mvar50==1] <- "Elite"
data$target[data$mvar51==1] <- "Credit"
length(data$target)
```
```{r}
num.na = sapply(data, function(x) sum(x==0))
percent.na =  num.na * 100  / nrow(data)
print("Percentage of NAs by columns: ")
print(percent.na)
```
```{r}
boxplot(data[,c(39,40,41,42,43,44)])
```

```{r}
num.na = sapply(data, function(x) sum(x==0))
percent.na =  num.na * 100  / nrow(data)
print("Percentage of NAs by columns: ")
print(percent.na)
```

```{r}
data$targetBin <- rep(0,nrow(data))
data$targetBin[data$mvar49==1] <- 1
data$targetBin[data$mvar50==1] <- 1
data$targetBin[data$mvar51==1] <- 1
length(data$targetBin)
```

```{r}
data$target <- as.factor(data$target)
data$targetBin <- as.factor(data$targetBin)
```

```{r}
barplot(table(data$target))
```
```{r}
barplot(table(data$targetBin))
```

```{r}
data <- data[, ! names(data) %in% c("mvar46"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar47"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar48"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar49"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar50"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar51"), drop = FALSE]
```

Negative values in Retail spending

```{r, eval=FALSE}
data <- data[, ! names(data) %in% c("mvar32"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar33"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar34"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar35"), drop = FALSE]
```

```{r}
head(data)
```
```{r}
data['ElectronicsSpend'] = data['mvar16']+data['mvar17']+data['mvar18']+data['mvar19']
data['TravelSpend'] = data['mvar20']+data['mvar21']+data['mvar22']+data['mvar23']
data['HouseholdSpend'] = data['mvar27']+data['mvar26']+data['mvar25']+data['mvar24']
data['CarSpend'] = data['mvar28']+data['mvar29']+data['mvar30']+data['mvar31']
data['RetailSpend'] = data['mvar32']+data['mvar33']+data['mvar34']+data['mvar35']
data['TotalSpend'] = data['mvar36']+data['mvar37']+data['mvar38']+data['mvar39']
```
```{r}
data <- data[, ! names(data) %in% c("mvar16"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar17"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar18"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar19"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar20"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar21"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar22"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar23"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar24"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar25"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar26"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar27"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar28"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar29"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar30"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar31"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar32"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar33"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar34"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar35"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar36"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar37"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar38"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar39"), drop = FALSE]
```

```{r}
v1 <- data$mvar40 + data$mvar41 + data$mvar42
v2 <- data$mvar43 + data$mvar44 + data$mvar45
data$card <- rep(0,nrow(data))
data$card[v1 > 0 & v2 == 0] <- 1
data$card[v1 == 0 & v2 > 0] <- 2
data$card[v1 > 0 & v2 > 0] <- 3
length(data$card)
```
```{r}
data <- data[, ! names(data) %in% c("mvar40"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar41"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar42"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar43"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar44"), drop = FALSE]
data <- data[, ! names(data) %in% c("mvar45"), drop = FALSE]
```
```{r}
data$card
```

```{r}
data <- data[, ! names(data) %in% c("target"), drop = FALSE]
bin <- data$targetBin 
data <- data[, ! names(data) %in% c("targetBin"), drop = FALSE]
data['targetBin'] <- bin
```

```{r}
bin <- data$target 
data <- data[, ! names(data) %in% c("target"), drop = FALSE]
data['target'] <- bin
```


```{r}
head(data)
```


```{r , echo=FALSE}
library(h2o)
h2o.init(nthreads=-1,max_mem_size="3g",enable_assertions=FALSE)
```
```{r}
str(data)
```

```{r}
data$mvar2 <- as.factor(data$mvar2)
data$mvar4 <- as.factor(data$mvar4)
data$mvar10 <- as.factor(data$mvar10)
data$mvar12 <- as.factor(data$mvar12)
data$mvar13 <- as.factor(data$mvar13)
data$mvar14 <- as.factor(data$mvar14)
data$mvar15 <- as.factor(data$mvar15)
# data$mvar40 <- as.factor(data$mvar40)
# data$mvar41 <- as.factor(data$mvar41)
# data$mvar42 <- as.factor(data$mvar42)
# data$mvar43 <- as.factor(data$mvar43)
# data$mvar44 <- as.factor(data$mvar44)
# data$mvar45 <- as.factor(data$mvar45)
data$card <- as.factor(data$card)
data$target <- as.factor(data$target)
```
```{r}
str(data)
```

```{r}
set.seed(1)
indexes = sample(1:nrow(data),size=0.2*nrow(data))
test=data[indexes,]
train=data[-indexes,]
```
```{r, echo=FALSE}
train.hex<-as.h2o(train)
test.hex<-as.h2o(test)
```
```{r}
# regression_model<-h2o.randomForest(
#     training_frame =train.hex,
#     validation_frame=test.hex,
#     x = -c(46),
#     y=45,
#     nfolds=10,
#     seed =100,
#     balance_classes= T,
#     binomial_double_trees = T,
#     ntrees = 150)
# print(regression_model)
```
 
```{r, echo=FALSE}
regression_model_multi<-h2o.randomForest(
    training_frame =train.hex,
    validation_frame=test.hex,
    
    y=22,
    
    seed =100,
    balance_classes= T,
    ntrees = 150)
```
```{r}
print(regression_model_multi)
```

```{r}
leader <- read.csv('Dataset/Leaderboard_Dataset.csv')
```
```{r}
cm_key <- leader['cm_key']
```


```{r}
leader <- leader[, ! names(leader) %in% c("mvar1"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("cm_key"), drop = FALSE]
```

Dropping retail spending (Score decreased to 30400 from 31000)

```{r, eval=FALSE}
leader <- leader[, ! names(leader) %in% c("mvar32"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar33"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar34"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar35"), drop = FALSE]
```

```{r}
leader$mvar2 <- as.factor(leader$mvar2)
leader$mvar4 <- as.factor(leader$mvar4)
leader$mvar10 <- as.factor(leader$mvar10)
leader$mvar12 <- as.factor(leader$mvar12)
leader$mvar13 <- as.factor(leader$mvar13)
leader$mvar14 <- as.factor(leader$mvar14)
leader$mvar15 <- as.factor(leader$mvar15)
# leader$mvar40 <- as.factor(leader$mvar40)
# leader$mvar41 <- as.factor(leader$mvar41)
# leader$mvar42 <- as.factor(leader$mvar42)
# leader$mvar43 <- as.factor(leader$mvar43)
# leader$mvar44 <- as.factor(leader$mvar44)
# leader$mvar45 <- as.factor(leader$mvar45)
```

```{r}
leader['ElectronicsSpend'] = leader['mvar16']+leader['mvar17']+leader['mvar18']+leader['mvar19']
leader['TravelSpend'] = leader['mvar20']+leader['mvar21']+leader['mvar22']+leader['mvar23']
leader['HouseholdSpend'] = leader['mvar27']+leader['mvar26']+leader['mvar25']+leader['mvar24']
leader['CarSpend'] = leader['mvar28']+leader['mvar29']+leader['mvar30']+leader['mvar31']
leader['RetailSpend'] = leader['mvar32']+leader['mvar33']+leader['mvar34']+leader['mvar35']
leader['TotalSpend'] = leader['mvar36']+leader['mvar37']+leader['mvar38']+leader['mvar39']
```
```{r}
leader <- leader[, ! names(leader) %in% c("mvar16"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar17"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar18"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar19"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar20"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar21"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar22"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar23"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar24"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar25"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar26"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar27"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar28"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar29"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar30"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar31"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar32"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar33"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar34"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar35"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar36"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar37"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar38"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar39"), drop = FALSE]
```


```{r}
v1 <- leader$mvar40 + leader$mvar41 + leader$mvar42
v2 <- leader$mvar43 + leader$mvar44 + leader$mvar45
leader$card <- rep(0,nrow(leader))
leader$card[v1 > 0 & v2 == 0] <- 1
leader$card[v1 == 0 & v2 > 0] <- 2
leader$card[v1 > 0 & v2 > 0] <- 3
length(leader$card)
```
```{r}
leader <- leader[, ! names(leader) %in% c("mvar40"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar41"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar42"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar43"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar44"), drop = FALSE]
leader <- leader[, ! names(leader) %in% c("mvar45"), drop = FALSE]
leader$card <- as.factor(leader$card)
```

```{r}
head(leader)
```

```{r}
leader.hex<-as.h2o(leader)
```
```{r}
predictions_binary <- as.data.frame(h2o.predict(regression_model_binary, leader.hex))
```
```{r}
predictions_binary["cm_key"] <- cm_key
```
```{r}
head(predictions_binary)
```

```{r}
pred <- data.frame(predictions_binary$Credit, predictions_binary$Elite, predictions_binary$Supp)
max<- do.call(pmax, pred)
max
predic <- colnames(pred)[apply(pred,1,which.max)]
p <- data.frame(predictions_binary$cm_key, predic, max)
head(p)
```
```{r}

p <- p[with(p, order(-max)), ]
p
```

```{r}
p <- p[1:1000,]
p
```
```{r}
p$predic <- gsub('predictions_binary.', '', p$predic)
p <- p[, ! names(p) %in% c("max"), drop = FALSE]
p
```



```{r}
predictions_binary <- predictions_binary[, ! names(predictions_binary) %in% c("p0"), drop = FALSE]
predictions_binary <- predictions_binary[, ! names(predictions_binary) %in% c("p1"), drop = FALSE]
```
```{r}
predictions_binary <- predictions_binary[c(2,1)]
```


```{r}
submission <- subset(predictions_binary, predict == 1)
```
```{r}
submission <- submission[1:1000,]
head(submission)
```
```{r}
submission$card <- rep("Supp",nrow(submission))
submission <- submission[, ! names(submission) %in% c("predict"), drop = FALSE]
head(submission)
```

```{r}
    write.table(p,file = "Envible_VITVellore_20.csv",sep = ",",row.names = FALSE, col.names = FALSE)
```

